### ISSUE TITLE
flash Generic-Switch-1-2-3-Pole-Glass

### ISSUE THREAD

**Issue by diotta88** [esphome/esphome-devices#283]
hello everyone, 
I have difficulty in flashing the wifi touch switch of which I am attaching photos, which should be the same as I find at the link:
https://github.com/esphome-devices/esphome-devices/tree/main/src/docs/devices/Generic-Switch-1-2-3-Pole-Glass

i tried tuya-convert, but it seems the version is too up to date (v1.1.2).

i also tried the photo links and tasmota web installer, but i can't write the firmware.

how can I do?

![IMG_1727](https://user-images.githubusercontent.com/57493234/191674160-be5e4735-8ea1-490f-acec-ccfd12456055.jpg)
![IMG_1731](https://user-images.githubusercontent.com/57493234/191674165-8b07f8e1-ddd9-4e2c-bb12-45c6c6e7a5a9.JPG)
![IMG_1737](https://user-images.githubusercontent.com/57493234/191674181-5c95c6a6-760b-431f-b6b3-71b7636c4876.jpg)
![IMG_1728](https://user-images.githubusercontent.com/57493234/191675475-daa7b976-5df9-4ef4-abca-794dcbe62c31.jpg)

**Comment by nagyrobi** [comment]
For faster answers, please head on to our support channel on Discord.
