### ISSUE TITLE
Shelly 1PM Plus (ESP32)

### ISSUE THREAD

**Issue by sanderlv** [esphome/esphome-devices#299]
Hi, how did you guys get the firmware on the Shelly? I tried to connect the pins, but they are so small. I managed to read out serial but did not get it in writable mode to upload the esphome bin. Please help...

https://github.com/esphome-devices/esphome-devices/blob/main/src/docs/devices/Shelly-Plus-1PM/index.md

@sairon
@tekmaven
@Mat931

Thanks!

**Comment by Mat931** [comment]
Hi @sanderlv 

Yes, the pins of the Shelly Plus are really small (1.27mm, half of the standard 2.54mm)
I'm using 2 female 2.54mm headers where I bent the pins 90°.

To put the ESP32 into download mode you need to connect GPIO0 to GND before powering it on. There is no auto reset circuit on the Shelly. You can use esptool to save the factory firmware to a file before flashing ESPHome. (esptool.py -p /dev/ttyUSB0 -b 115200 read_flash 0 0x400000 firmware.bin)

If you're getting errors you need a better power supply. The FTDI USB to Serial adapter can't supply enough current to power the ESP32. I connected 24V DC to the screw terminals and left the FTDI adapter's 3.3V pin disconnected. You could probably also use a better 3.3V power supply. Don't connect it to mains for flashing!

![1](https://user-images.githubusercontent.com/49403702/199280162-c895e795-4e05-478f-b75e-a00513230840.jpg)
![3](https://user-images.githubusercontent.com/49403702/199280217-347ce7f3-9323-4a45-8e51-89b4d5a6de1e.jpg)

**Comment by sanderlv** [comment]
Hi, thanks for this great reply! Can you please elaborate on this: To put the ESP32 into download mode you need to connect GPIO0 to GND before powering it on.

Do you mean to pull down gpio0 on powering on and after powering on disconnect gpio0 from gnd? Or keep it connected. The latter I believe I tried but did not work yet.

**Comment by Mat931** [comment]
I think it's okay to disconnect GPIO0 once the ESP32 is powered on.
You can also try the following:

- Connect GND, TX, RX to the FTDI adapter
- Connect power
- Pull down GPIO0 to GND
- Pull down EN to GND
- Release EN
- Release GPIO0
- Read / Flash the firmware

I don't remember exactly how I did it. It's been almost a year since I flashed my Shellys and now they are hidden in the walls :)

**Comment by sanderlv** [comment]
cant get it going., according to here EN should be puled up???

https://templates.blakadder.com/shelly_plus_1PM.html

**Comment by Mat931** [comment]
Don't worry about pulling up EN. There's a pull-up resistor somewhere on the board. If you pull EN down and release it you can reboot the ESP32 without disconnecting power every time.

Maybe check your wires. Can you share more info about your setup and the error messages?

**Comment by sanderlv** [comment]
Dont know what or how I did it but suddenly it flashed... now red light blinks after power on but no response... no logging and no wifi...

**Comment by sanderlv** [comment]
Some more logging but no wifi

Using 'COM6' as serial port.
Showing logs:
[20:26:02][D][hlw8012:082]: Got power=0.0W, voltage=0.0V
[20:26:02][D][sensor:127]: 'shelly-plus-1pm-01 Voltage': Sending state 0.00000 V with 1 decimals of accuracy
[20:26:02][D][sensor:127]: 'shelly-plus-1pm-01 Power': Sending state 0.00000 W with 1 decimals of accuracy
[20:26:02][D][sensor:127]: 'shelly-plus-1pm-01 Daily energy consumed': Sending state 0.00000 kWh with 3 decimals of accuracy
[20:26:07][D][sensor:127]: 'shelly-plus-1pm-01 Relay Supply Voltage': Sending state 3.01600 V with 2 decimals of accuracy
[20:26:12][D][hlw8012:082]: Got power=0.0W, voltage=0.0V
[20:26:12][D][sensor:127]: 'shelly-plus-1pm-01 Voltage': Sending state 0.03046 V with 1 decimals of accuracy
[20:26:12][D][sensor:127]: 'shelly-plus-1pm-01 Power': Sending state 0.00000 W with 1 decimals of accuracy
[20:26:12][D][sensor:127]: 'shelly-plus-1pm-01 Daily energy consumed': Sending state 0.00000 kWh with 3 decimals of accuracy
[20:26:22][D][sensor:127]: 'shelly-plus-1pm-01 Power': Sending state 0.00000 W with 1 decimals of accuracy
[20:26:22][D][sensor:127]: 'shelly-plus-1pm-01 Daily energy consumed': Sending state 0.00000 kWh with 3 decimals of accuracy
[20:26:27][D][esp32.preferences:113]: Saving 3 preferences to flash...
[20:26:27][D][esp32.preferences:142]: Saving 3 preferences to flash: 3 cached, 0 written, 0 failed
[20:26:29][D][sensor:127]: 'temp_analog_reading': Sending state 1.50200 V with 2 decimals of accuracy
[20:26:29][D][resistance:039]: 'temp_resistance_reading' - Resistance 8353.7Ω
[20:26:29][D][sensor:127]: 'temp_resistance_reading': Sending state 8353.72656 Ω with 1 decimals of accuracy
[20:26:29][D][ntc:026]: 'shelly-plus-1pm-01 Temperature' - Temperature: 29.9°C
[20:26:29][D][sensor:127]: 'shelly-plus-1pm-01 Temperature': Sending state 29.85077 °C with 1 decimals of accuracy
[20:26:32][D][hlw8012:076]: Got power=0.0W, current=0.0A
[20:26:32][D][sensor:127]: 'shelly-plus-1pm-01 Current': Sending state 0.00000 A with 3 decimals of accuracy
[20:26:32][D][sensor:127]: 'shelly-plus-1pm-01 Power': Sending state 0.00000 W with 1 decimals of accuracy
[20:26:32][D][sensor:127]: 'shelly-plus-1pm-01 Daily energy consumed': Sending state 0.00000 kWh with 3 decimals of accuracy
[20:26:42][D][hlw8012:076]: Got power=0.0W, current=0.0A

**Comment by Mat931** [comment]
Great! ESPHome is working. You can check your wifi settings (maybe on a different ESP that's easier to flash) and then upload the new settings to the Shelly

**Comment by sanderlv** [comment]
Think I got some running

![image](https://user-images.githubusercontent.com/16528916/199586409-9d7e9fd5-8e3c-461a-a351-05dbc2d8de9c.png)

**Comment by sanderlv** [comment]
Hmz... now the main reason for having an ESP32 Shelly... Ble proxy...

Giving an error:

```
INFO Reading configuration /config/esphome/shelly-plus-1pm-01.yaml...
INFO Detected timezone 'Europe/Amsterdam'
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing shelly-plus-1pm-01 (board: esp32doit-devkit-v1; framework: espidf; platform: platformio/espressif32 @ 3.5.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40302.0 (4.3.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch2 
 - toolchain-xtensa-esp32s2 @ 8.4.0+2021r2-patch2
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
No dependencies
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/adc/adc_sensor.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/api_connection.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/api_frame_helper.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/api_pb2.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/api_pb2_service.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/api_server.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/list_entities.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/proto.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/subscribe_state.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/api/user_services.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/binary_sensor/automation.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/binary_sensor/binary_sensor.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/binary_sensor/filter.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/bluetooth_proxy/bluetooth_proxy.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32/core.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32/gpio_arduino.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32/gpio_idf.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32/preferences.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32_ble_client/ble_characteristic.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32_ble_client/ble_client_base.o
src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp: In member function 'virtual void esphome::bluetooth_proxy::BluetoothProxy::gattc_event_handler(esp_gattc_cb_event_t, esp_gatt_if_t, esp_ble_gattc_cb_param_t*)':
src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:69:22: warning: this statement may fall through [-Wimplicit-fallthrough=]
       this->address_ = 0;
       ~~~~~~~~~~~~~~~^~~
src/esphome/components/bluetooth_proxy/bluetooth_proxy.cpp:71:5: note: here
     case ESP_GATTC_OPEN_EVT: {
     ^~~~
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32_ble_client/ble_service.o
src/esphome/components/esp32_ble_client/ble_client_base.cpp: In member function 'float esphome::esp32_ble_client::BLEClientBase::parse_char_value(uint8_t*, uint16_t)':
src/esphome/components/esp32_ble_client/ble_client_base.cpp:220:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:223:5: note: here
     case 0x7:  // uint24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:224:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:227:5: note: here
     case 0x8:  // uint32.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:228:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 4) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:231:5: note: here
     case 0xC:  // int8.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:235:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 2) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:238:5: note: here
     case 0xF:  // int24.
     ^~~~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:239:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (length > 3) {
       ^~
src/esphome/components/esp32_ble_client/ble_client_base.cpp:242:5: note: here
     case 0x10:  // int32.
     ^~~~
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/gpio/output/gpio_binary_output.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/hlw8012/hlw8012.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/homeassistant/time/homeassistant_time.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/logger/logger.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/md5/md5.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/mdns/mdns_component.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/mdns/mdns_esp32_arduino.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/mdns/mdns_esp8266.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/mdns/mdns_esp_idf.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/network/util.o
Compiling /data/shelly-plus-1pm-01/.pioenvs/shelly-plus-1pm-01/src/esphome/components/ntc/ntc.o...
```

**Comment by Mat931** [comment]
I haven't tried Bluetooth on the Shelly but here's more info: https://community.home-assistant.io/t/shelly-plus-1-esphome-bletracker/363549/41

**Comment by sanderlv** [comment]
Hmz... back again. It comes online for a while but then becomes unavailable forever...
