### ISSUE TITLE
Shelly Plus 2PM, single core compilation issues

### ISSUE THREAD

**Issue by Rvh91** [esphome/esphome-devices#353]
Hi, I'm encountering some issues with compilations errors that seem to be unique to my single core shelly plus 2pm.
I don't really know how to debug it however.

I've copied over the following in the start of the config:

```
# For Single Core ESP32
esphome:
  name: ${node_name}
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
```

For certain components I get compilation errors that I dont get on other devices. To me it seems related to maybe the esp-idf, or other options that other devices dont need. But I couldn't find anything in the docs about this. I was hoping someone could help me out with solving these issues, or steer me in the right direction.

It occurs for the following components:
time.sntp
```
time:     #needed for energy integration
   - platform: sntp
```
which gives the compilation error:
`
Compiling /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o)
Linking /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf)
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0xa8):](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0xa8):) undefined reference to `vtable for esphome::sntp::SNTPComponent'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0x314):](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0x314):) undefined reference to `esphome::time::RealTimeClock::RealTimeClock()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o): in function `std::_Deque_base<esphome::esp32_ble_tracker::BLEEvent*, std::allocator<esphome::esp32_ble_tracker::BLEEvent*> >::_Deque_impl::_Deque_impl()':
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_deque.h:560: undefined reference to `esphome::time::RealTimeClock::RealTimeClock()'
collect2: error: ld returned 1 exit status
*** [/[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf)] Error 1
========================= [FAILED] Took 132.38 seconds =========================
`

time.homeassistant:
```
time: #needed for energy integration
  - platform: homeassistant
    id: homeassistant_time   
```

`
Dependency Graph
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o
Linking /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection20on_get_time_responseERKNS0_15GetTimeResponseE+0x0): undefined reference to `esphome::homeassistant::global_homeassistant_time'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection20on_get_time_responseERKNS0_15GetTimeResponseE+0x4): undefined reference to `esphome::time::RealTimeClock::synchronize_epoch_(unsigned int)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/esphome/components/api/api_connection.o: in function `esphome::homeassistant::HomeassistantTime::set_epoch_time(unsigned int)':
/config/esphome/.esphome/build/shelly-plus-2pm/src/esphome/components/homeassistant/time/homeassistant_time.h:15: undefined reference to `esphome::time::RealTimeClock::synchronize_epoch_(unsigned int)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0xa8): undefined reference to `vtable for esphome::homeassistant::HomeassistantTime'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o:(.literal._Z5setupv+0x308): undefined reference to `esphome::time::RealTimeClock::RealTimeClock()'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o: in function `std::_Vector_base<esphome::esp32_ble_tracker::ESPBTClient*, std::allocator<esphome::esp32_ble_tracker::ESPBTClient*> >::_Vector_impl::_Vector_impl()':
/data/cache/platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/stl_vector.h:96: undefined reference to `esphome::time::RealTimeClock::RealTimeClock()'
collect2: error: ld returned 1 exit status
*** [/data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/firmware.elf] Error 1
========================= [FAILED] Took 65.27 seconds =========================
`

wifi channel:
```
sensor:
  - platform: template
    name: ${node_name} Wifi Channel
    lambda: return wifi.channel();
    update_interval: 180s
```

`
Compiling /[data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o](http://data/shelly-plus-2pm/.pioenvs/shelly-plus-2pm/src/main.o)
/config/esphome/shelly-plus-2pm.yaml: In lambda function:
/config/esphome/shelly-plus-2pm.yaml:199:18: error: expected primary-expression before '.' token
     lambda: return wifi.channel();
`

**Comment by nagyrobi** [comment]
For faster answers, please head on to our support channel on Discord.
