### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nagyrobi** [esphome/esphome-devices#388]
@tekmaven the recent [pull](https://github.com/esphome/esphome-devices/pull/387) worked fine on the [deploy-preview](https://deploy-preview-387--esphome-devices.netlify.app/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation) but not on the [main site](https://devices.esphome.io/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation). Runs on error 404.
Any idea why?

**Comment by tekmaven** [comment]
https://devices.esphome.io/devices/Genvex-Nibe-AlphaInnotec-heat-recovery-ventilation does load for me.  There is heavy caching on the site, so it may take a little time, and you may have cached a 404 at that url.
